"""baseline_init

Revision ID: 00d704753e02
Revises: 
Create Date: 2026-04-21 03:00:57.786198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00d704753e02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('slug', name=op.f('uq_articles_slug'))
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('chat_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_pattern', sa.String(length=255), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('sub_intent', sa.String(length=100), nullable=True),
    sa.Column('answer_title', sa.String(length=255), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('suggested_actions_json', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_faqs'))
    )
    op.create_index(op.f('ix_chat_faqs_id'), 'chat_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_faqs_intent'), 'chat_faqs', ['intent'], unique=False)
    op.create_index(op.f('ix_chat_faqs_normalized_question'), 'chat_faqs', ['normalized_question'], unique=False)
    op.create_index(op.f('ix_chat_faqs_sub_intent'), 'chat_faqs', ['sub_intent'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_user_message', sa.String(length=1000), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads'))
    )
    op.create_index(op.f('ix_chat_threads_id'), 'chat_threads', ['id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('frame_trend_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=50), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('winning_frame', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frame_trend_inputs')),
    sa.UniqueConstraint('target_date', 'venue', 'race_number', name='uq_frame_trend_input_target_date_venue_race_number')
    )
    op.create_index(op.f('ix_frame_trend_inputs_id'), 'frame_trend_inputs', ['id'], unique=False)
    op.create_index(op.f('ix_frame_trend_inputs_target_date'), 'frame_trend_inputs', ['target_date'], unique=False)
    op.create_index(op.f('ix_frame_trend_inputs_venue'), 'frame_trend_inputs', ['venue'], unique=False)
    op.create_table('frame_trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('race_scope', sa.String(length=100), nullable=True),
    sa.Column('lucky_frame', sa.Integer(), nullable=True),
    sa.Column('trend_summary', sa.String(length=255), nullable=True),
    sa.Column('trend_note', sa.Text(), nullable=True),
    sa.Column('recommended_style', sa.String(length=20), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('win_frame_data', sa.Text(), nullable=True),
    sa.Column('place_frame_data', sa.Text(), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frame_trend_snapshots'))
    )
    op.create_index(op.f('ix_frame_trend_snapshots_id'), 'frame_trend_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_frame_trend_snapshots_target_date'), 'frame_trend_snapshots', ['target_date'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('publish_start_at', sa.DateTime(), nullable=True),
    sa.Column('publish_end_at', sa.DateTime(), nullable=True),
    sa.Column('sold_out', sa.Boolean(), nullable=True),
    sa.Column('sold_out_at', sa.DateTime(), nullable=True),
    sa.Column('race_count', sa.Integer(), nullable=True),
    sa.Column('race_date', sa.String(length=50), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('expected_return', sa.Integer(), nullable=True),
    sa.Column('max_return', sa.Integer(), nullable=True),
    sa.Column('recommended_amount', sa.String(length=100), nullable=True),
    sa.Column('recommended_race_count', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('race_change_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.Column('race_course', sa.String(length=100), nullable=True),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('previous_surface', sa.String(length=20), nullable=True),
    sa.Column('current_surface', sa.String(length=20), nullable=True),
    sa.Column('previous_distance', sa.Integer(), nullable=True),
    sa.Column('current_distance', sa.Integer(), nullable=True),
    sa.Column('previous_jockey', sa.String(length=100), nullable=True),
    sa.Column('current_jockey', sa.String(length=100), nullable=True),
    sa.Column('surface_changed', sa.Boolean(), nullable=True),
    sa.Column('distance_changed', sa.Boolean(), nullable=True),
    sa.Column('distance_direction', sa.String(length=20), nullable=True),
    sa.Column('gear_changed', sa.Boolean(), nullable=True),
    sa.Column('jockey_changed', sa.Boolean(), nullable=True),
    sa.Column('class_changed', sa.Boolean(), nullable=True),
    sa.Column('change_summary', sa.String(length=255), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_change_highlights'))
    )
    op.create_index(op.f('ix_race_change_highlights_id'), 'race_change_highlights', ['id'], unique=False)
    op.create_index(op.f('ix_race_change_highlights_target_date'), 'race_change_highlights', ['target_date'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_key', sa.String(length=64), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=50), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('course_class', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_index(op.f('ix_races_race_date'), 'races', ['race_date'], unique=False)
    op.create_index(op.f('ix_races_race_key'), 'races', ['race_key'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('catch_copy', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('affiliate_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('hit_amount', sa.BigInteger(), nullable=False),
    sa.Column('hit_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recovery_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('style_type', sa.String(length=50), nullable=True),
    sa.Column('free_level', sa.String(length=50), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('slug', name=op.f('uq_sites_slug'))
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('register_status', sa.Enum('temp', 'active', 'suspended', 'withdrawn', name='registerstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='paymentstatus'), nullable=False),
    sa.Column('total_payment', sa.Integer(), nullable=True),
    sa.Column('last_access_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('action_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('login', 'view_free', 'view_paid', 'click', name='actiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_logs'))
    )
    op.create_index('idx_user_action', 'action_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('normalized_question', sa.String(length=500), nullable=True),
    sa.Column('answered_by', sa.String(length=50), nullable=True),
    sa.Column('source_summary', sa.String(length=255), nullable=True),
    sa.Column('suggested_actions_json', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_messages_thread_id_chat_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_answered_by'), 'chat_messages', ['answered_by'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_intent'), 'chat_messages', ['intent'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('hit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=True),
    sa.Column('hit_amount', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_hit_results_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hit_results'))
    )
    op.create_table('ip_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Enum('register', 'access', name='iptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ip_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_logs'))
    )
    op.create_index('idx_ip', 'ip_logs', ['ip_address'], unique=False)
    op.create_index('idx_user_ip', 'ip_logs', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('credit', 'bank', 'amazonpay', name='paymentmethod'), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'pending', name='paymentstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('idx_user_paid', 'payments', ['user_id', 'paid_at'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('free', 'paid', name='pointtype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_points_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points'))
    )
    op.create_index('idx_user_point', 'points', ['user_id'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('horse_key', sa.String(length=64), nullable=False),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('horse_number', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('jockey_name', sa.String(length=100), nullable=True),
    sa.Column('trainer_name', sa.String(length=100), nullable=True),
    sa.Column('handicap_weight', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('blinkers_now', sa.Boolean(), nullable=False),
    sa.Column('odds', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_entries_race_id_races')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_entries')),
    sa.UniqueConstraint('race_id', 'horse_key', name='uq_race_entries_race_horse')
    )
    op.create_index(op.f('ix_race_entries_horse_key'), 'race_entries', ['horse_key'], unique=False)
    op.create_index(op.f('ix_race_entries_race_id'), 'race_entries', ['race_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reviews_product_id_products')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_reviews_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('user_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tags_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tags')),
    sa.UniqueConstraint('user_id', 'tag', name='uq_user_tag')
    )
    op.create_index('idx_tag', 'user_tags', ['tag'], unique=False)
    op.create_index('idx_user_tag_user', 'user_tags', ['user_id'], unique=False)
    op.create_table('chat_question_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('sub_intent', sa.String(length=100), nullable=True),
    sa.Column('answered_by', sa.String(length=50), nullable=True),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.Column('is_answered_successfully', sa.Boolean(), nullable=False),
    sa.Column('needs_improvement', sa.Boolean(), nullable=False),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['chat_faqs.id'], name=op.f('fk_chat_question_logs_faq_id_chat_faqs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_chat_question_logs_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_question_logs_thread_id_chat_threads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_question_logs'))
    )
    op.create_index(op.f('ix_chat_question_logs_answered_by'), 'chat_question_logs', ['answered_by'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_faq_id'), 'chat_question_logs', ['faq_id'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_id'), 'chat_question_logs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_intent'), 'chat_question_logs', ['intent'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_message_id'), 'chat_question_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_normalized_question'), 'chat_question_logs', ['normalized_question'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_sub_intent'), 'chat_question_logs', ['sub_intent'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_thread_id'), 'chat_question_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_question_logs_user_id'), 'chat_question_logs', ['user_id'], unique=False)
    op.create_table('condition_change_horses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('race_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('horse_key', sa.String(length=64), nullable=False),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('prev_race_date', sa.Date(), nullable=True),
    sa.Column('prev_race_name', sa.String(length=255), nullable=True),
    sa.Column('prev_surface', sa.String(length=20), nullable=True),
    sa.Column('prev_distance', sa.Integer(), nullable=True),
    sa.Column('prev_finish_position', sa.Integer(), nullable=True),
    sa.Column('current_surface', sa.String(length=20), nullable=False),
    sa.Column('current_distance', sa.Integer(), nullable=False),
    sa.Column('distance_diff', sa.Integer(), nullable=False),
    sa.Column('surface_changed', sa.Boolean(), nullable=False),
    sa.Column('blinkers_first_time', sa.Boolean(), nullable=False),
    sa.Column('blinkers_reapplied', sa.Boolean(), nullable=False),
    sa.Column('blinkers_removed', sa.Boolean(), nullable=False),
    sa.Column('layoff_days', sa.Integer(), nullable=True),
    sa.Column('change_flags', mysql.JSON(), nullable=False),
    sa.Column('change_score', sa.Integer(), nullable=False),
    sa.Column('short_comment', sa.String(length=500), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], name=op.f('fk_condition_change_horses_race_entry_id_race_entries')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_condition_change_horses_race_id_races')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condition_change_horses'))
    )
    op.create_index(op.f('ix_condition_change_horses_batch_date'), 'condition_change_horses', ['batch_date'], unique=False)
    op.create_index(op.f('ix_condition_change_horses_horse_key'), 'condition_change_horses', ['horse_key'], unique=False)
    op.create_index(op.f('ix_condition_change_horses_is_featured'), 'condition_change_horses', ['is_featured'], unique=False)
    op.create_index(op.f('ix_condition_change_horses_race_entry_id'), 'condition_change_horses', ['race_entry_id'], unique=False)
    op.create_index(op.f('ix_condition_change_horses_race_id'), 'condition_change_horses', ['race_id'], unique=False)
    op.create_table('review_helpful_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('device_id_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_helpful_votes_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_helpful_votes')),
    sa.UniqueConstraint('review_id', 'device_id_hash', name='uq_review_helpful_vote_review_device')
    )
    op.create_index(op.f('ix_review_helpful_votes_device_id_hash'), 'review_helpful_votes', ['device_id_hash'], unique=False)
    op.create_index(op.f('ix_review_helpful_votes_id'), 'review_helpful_votes', ['id'], unique=False)
    op.create_index(op.f('ix_review_helpful_votes_review_id'), 'review_helpful_votes', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_helpful_votes_review_id'), table_name='review_helpful_votes')
    op.drop_index(op.f('ix_review_helpful_votes_id'), table_name='review_helpful_votes')
    op.drop_index(op.f('ix_review_helpful_votes_device_id_hash'), table_name='review_helpful_votes')
    op.drop_table('review_helpful_votes')
    op.drop_index(op.f('ix_condition_change_horses_race_id'), table_name='condition_change_horses')
    op.drop_index(op.f('ix_condition_change_horses_race_entry_id'), table_name='condition_change_horses')
    op.drop_index(op.f('ix_condition_change_horses_is_featured'), table_name='condition_change_horses')
    op.drop_index(op.f('ix_condition_change_horses_horse_key'), table_name='condition_change_horses')
    op.drop_index(op.f('ix_condition_change_horses_batch_date'), table_name='condition_change_horses')
    op.drop_table('condition_change_horses')
    op.drop_index(op.f('ix_chat_question_logs_user_id'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_thread_id'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_sub_intent'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_normalized_question'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_message_id'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_intent'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_id'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_faq_id'), table_name='chat_question_logs')
    op.drop_index(op.f('ix_chat_question_logs_answered_by'), table_name='chat_question_logs')
    op.drop_table('chat_question_logs')
    op.drop_index('idx_user_tag_user', table_name='user_tags')
    op.drop_index('idx_tag', table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_race_entries_race_id'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_horse_key'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index('idx_user_point', table_name='points')
    op.drop_table('points')
    op.drop_index('idx_user_paid', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_user_ip', table_name='ip_logs')
    op.drop_index('idx_ip', table_name='ip_logs')
    op.drop_table('ip_logs')
    op.drop_table('hit_results')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_intent'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_answered_by'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_user_action', table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_races_race_key'), table_name='races')
    op.drop_index(op.f('ix_races_race_date'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_race_change_highlights_target_date'), table_name='race_change_highlights')
    op.drop_index(op.f('ix_race_change_highlights_id'), table_name='race_change_highlights')
    op.drop_table('race_change_highlights')
    op.drop_table('products')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_frame_trend_snapshots_target_date'), table_name='frame_trend_snapshots')
    op.drop_index(op.f('ix_frame_trend_snapshots_id'), table_name='frame_trend_snapshots')
    op.drop_table('frame_trend_snapshots')
    op.drop_index(op.f('ix_frame_trend_inputs_venue'), table_name='frame_trend_inputs')
    op.drop_index(op.f('ix_frame_trend_inputs_target_date'), table_name='frame_trend_inputs')
    op.drop_index(op.f('ix_frame_trend_inputs_id'), table_name='frame_trend_inputs')
    op.drop_table('frame_trend_inputs')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_chat_faqs_sub_intent'), table_name='chat_faqs')
    op.drop_index(op.f('ix_chat_faqs_normalized_question'), table_name='chat_faqs')
    op.drop_index(op.f('ix_chat_faqs_intent'), table_name='chat_faqs')
    op.drop_index(op.f('ix_chat_faqs_id'), table_name='chat_faqs')
    op.drop_table('chat_faqs')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
