"""create chat_messages table

Revision ID: 040a49ea69ac
Revises: f1d1fd3ec28a
Create Date: 2026-01-28 17:26:13.263253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '040a49ea69ac'
down_revision: Union[str, None] = 'f1d1fd3ec28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.alter_column('hit_results', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    op.alter_column('hit_results', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
