"""add operation_logs

Revision ID: 55a167691f1d
Revises: ba9046b561e0
Create Date: 2026-01-24 10:41:32.867836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55a167691f1d'
down_revision: Union[str, None] = 'ba9046b561e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_logs')
    op.drop_index('email', table_name='admins')
    op.drop_table('admins')
    op.alter_column('users', 'total_payment',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('idx_email', table_name='users')
    op.drop_index('idx_payment_status', table_name='users')
    op.drop_index('idx_register_status', table_name='users')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.ENUM('male', 'female', 'other', collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('users', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('idx_register_status', 'users', ['register_status'], unique=False)
    op.create_index('idx_payment_status', 'users', ['payment_status'], unique=False)
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'total_payment',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('role', mysql.ENUM('super_admin', 'operator', 'viewer'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'admins', ['email'], unique=True)
    op.create_table('operation_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('admin_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('target_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('target_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('detail', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
