"""init

Revision ID: ba9046b561e0
Revises: 
Create Date: 2026-01-23 14:29:54.279720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9046b561e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('register_status', sa.Enum('temp', 'active', 'suspended', 'withdrawn', name='registerstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='paymentstatus'), nullable=False),
    sa.Column('total_payment', sa.Integer(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_payment_status', 'users', ['payment_status'], unique=False)
    op.create_index('idx_register_status', 'users', ['register_status'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('login', 'view_free', 'view_paid', 'click', name='actiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_logs'))
    )
    op.create_index('idx_user_action', 'action_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('ip_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Enum('register', 'access', name='iptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ip_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_logs'))
    )
    op.create_index('idx_ip', 'ip_logs', ['ip_address'], unique=False)
    op.create_index('idx_user_ip', 'ip_logs', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('credit', 'bank', 'amazonpay', name='paymentmethod'), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'pending', name='paymentstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('idx_user_paid', 'payments', ['user_id', 'paid_at'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('free', 'paid', name='pointtype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_points_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points'))
    )
    op.create_index('idx_user_point', 'points', ['user_id'], unique=False)
    op.create_table('user_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tags_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tags')),
    sa.UniqueConstraint('user_id', 'tag', name='uq_user_tag')
    )
    op.create_index('idx_tag', 'user_tags', ['tag'], unique=False)
    op.create_index('idx_user_tag_user', 'user_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_tag_user', table_name='user_tags')
    op.drop_index('idx_tag', table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index('idx_user_point', table_name='points')
    op.drop_table('points')
    op.drop_index('idx_user_paid', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_user_ip', table_name='ip_logs')
    op.drop_index('idx_ip', table_name='ip_logs')
    op.drop_table('ip_logs')
    op.drop_index('idx_user_action', table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index('idx_register_status', table_name='users')
    op.drop_index('idx_payment_status', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
